#!/bin/bash
if [[ -e MadLoop5_resources.tar.gz && ! -e MadLoop5_resources ]]; then
tar -xzf MadLoop5_resources.tar.gz
fi
k=run1_app.log
script=ajob6                         
j=G1.0449
     if [[ ! -e $j ]]; then
          mkdir $j
     fi
     cd $j
     rm -f $k
     if  [[ -e ftn26 ]]; then
          cp ftn26 ftn25
     fi
     if [[ ! -e ftn25 ]]; then
         echo "    1000       9       1" >& input_sg.txt
         echo " -0.55298E+03" >> input_sg.txt
         echo "2" >> input_sg.txt
         echo "1" >> input_sg.txt
         echo "   0 " >> input_sg.txt
         echo "1.0449" >>input_sg.txt
          for((try=1;try<=16;try+=1)); 
          do
          ../madevent >> $k <input_sg.txt
          if [ -s $k ]
          then
              break
          else
              echo $try > fail.log 
          fi
          done
     echo "" >> $k; echo "ls status:" >> $k; ls >> $k
          cat $k >> log.txt
          if [[ -e ftn26 ]]; then
               cp ftn26 ftn25
          fi
     else
          rm -f $k
         echo "    1000       9       1" >& input_sg.txt
         echo " -0.55298E+03" >> input_sg.txt
         echo "0" >> input_sg.txt
         echo "1" >> input_sg.txt
         echo "   0 " >> input_sg.txt
         echo "1.0449" >>input_sg.txt
          if [[ -e ftn26 ]]; then
               cp ftn26 ftn25
          fi
          for((try=1;try<=16;try+=1)); 
          do
          ../madevent >> $k <input_sg.txt
          if [ -s $k ]
          then
              break
          else
              echo $try > fail.log 
          fi
          done
     echo "" >> $k; echo "ls status:" >> $k; ls >> $k
          cat $k >> log.txt
     fi
     cd ../
