C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/10,9/
      DATA (SPROP(I,-1,1),I=1,4)/24,24,24,24/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/8,7/
      DATA (SPROP(I,-2,1),I=1,4)/-24,-24,-24,-24/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/-1,-2/
      DATA (SPROP(I,-3,1),I=1,4)/25,25,25,25/
      DATA TPRID(-3,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/6,3/
      DATA (SPROP(I,-4,1),I=1,4)/-24,-24,-24,-24/
      DATA TPRID(-4,1)/0/
      DATA (IFOREST(I,-5,1),I=1,2)/5,4/
      DATA (SPROP(I,-5,1),I=1,4)/24,24,24,24/
      DATA TPRID(-5,1)/0/
      DATA (IFOREST(I,-6,1),I=1,2)/-5,-4/
      DATA (SPROP(I,-6,1),I=1,4)/25,25,25,25/
      DATA TPRID(-6,1)/0/
      DATA (IFOREST(I,-7,1),I=1,2)/-3,-6/
      DATA (SPROP(I,-7,1),I=1,4)/35,35,35,35/
      DATA TPRID(-7,1)/0/
C     Number of configs
      DATA MAPCONFIG(0)/1/
