ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of heft_radion'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_55 = ', GC_55
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_46 = ', GC_46
      WRITE(*,2) 'GC_47 = ', GC_47
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_59 = ', GC_59
