ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3)

      DOUBLE PRECISION MDL_MP,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC
     $ ,MDL_MB,MDL_ME,MDL_MH,MDL_MM,MDL_MH02

      COMMON/MASSES/ MDL_MP,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC,MDL_MB
     $ ,MDL_ME,MDL_MH,MDL_MM,MDL_MH02


      DOUBLE PRECISION MDL_WH1,MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_WH02
     $ ,MDL_WH

      COMMON/WIDTHS/ MDL_WH1,MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_WH02
     $ ,MDL_WH


      DOUBLE COMPLEX GC_55, GC_18, GC_19, GC_20, GC_21, GC_22, GC_23,
     $  GC_37, GC_45, GC_46, GC_47, GC_48, GC_49, GC_50, GC_58, GC_59

      COMMON/COUPLINGS/ GC_55, GC_18, GC_19, GC_20, GC_21, GC_22,
     $  GC_23, GC_37, GC_45, GC_46, GC_47, GC_48, GC_49, GC_50, GC_58,
     $  GC_59

